# Site Settings
title: Xiaofeng Mao
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: 毛潇锋
tagline: 研究生在读
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '我的研究方向是迁移学习（视觉域适应）以及视觉目标跟踪。主要针对某一具体问题 （分类，检测，跟踪等），由某一个数据域的先验解决另一个域上的同类型问题。当 前我致力于红外目标跟踪领域的研究并且正在为年初的计算机视觉顶级会议做准备。 同时我也关注图像合成技术的最新研究进展，包括生成对抗网络（GAN）以及风格迁移。更多细节请访问我的<a href="https://www.zhihu.com/people/mao-xiao-feng-29-7/activities">知乎主页</a>.'

#sidebar links
email: hzmaoxiaofeng@163.com
phone: 188 0462 1729
website: blog.csdn.net/mao_xiao_feng #do not add http://
github: github.com/xfmao
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
